##=====log common=====##
logging:
  level:
    # control root logger's level for INFO
    root: INFO
    # control org.springframework logger's level for DEBUG
    org:
      springframework: INFO

spring:
  cloud:
    ##=====consul=====##
    consul:
      host: 127.0.0.1
      port: 0000

  ##=====mongodb config=====##
  data:
    mongodb:
      host: 127.0.0.1
      port: 123456
      username: xxxx
      password: xxxx
      database: xxxx
      authentication-database: xxxx